#ifndef TRANSPORTINFRA_GLOBAL_H
#define TRANSPORTINFRA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSPORTINFRA_LIBRARY)
#  define TRANSPORTINFRA_EXPORT Q_DECL_EXPORT
#else
#  define TRANSPORTINFRA_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSPORTINFRA_GLOBAL_H
