#ifndef UTILITIESINFRA_GLOBAL_H
#define UTILITIESINFRA_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UTILITIESINFRA_LIBRARY)
#  define UTILITIESINFRA_EXPORT Q_DECL_EXPORT
#else
#  define UTILITIESINFRA_EXPORT Q_DECL_IMPORT
#endif

#endif // UTILITIESINFRA_GLOBAL_H
